sudo: required
services:
    - docker

before_install:
    - docker build -t eltabakh/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true eltabakh/docker-react npm run test -- --coverage
