sudo: required
services:
    - docker

before_install:
    - docker build -t eltabakh/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true eltabakh/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "docker_react"
    env: "DockerReact-env-2"
    bucket_name: elasticbeanstalk-eu-west-1-818193600336
    #bucket_path: "resources/environments/e-s3jnarvjsa/_runtime/_versions/docker_react"
    on:
        branch: master
    #access_key_id: $AWS_ACCESS_KEY
    #secret_access_key:
        #secure: "$AWS_SECRET_KEY"
